#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 7
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 1,
  aux_sym_fence_token1 = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LF = 5,
  anon_sym_COLON = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_DASH = 12,
  anon_sym_PLUS = 13,
  aux_sym_binary_operator_token1 = 14,
  anon_sym_STAR_STAR = 15,
  anon_sym_COLON_EQ = 16,
  anon_sym_DASH_GT = 17,
  anon_sym_BANG_EQ = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_LT_LT = 21,
  anon_sym_GT_GT = 22,
  anon_sym_SLASH_SLASH = 23,
  anon_sym_SLASH_STAR = 24,
  anon_sym_SLASH_AT = 25,
  sym_literal = 26,
  anon_sym_BQUOTE = 27,
  sym_inline_latex_token = 28,
  sym_block_latex_token = 29,
  sym__anyword = 30,
  sym__newline = 31,
  sym__indent = 32,
  sym__dedent = 33,
  sym__string_start = 34,
  sym__string_content = 35,
  sym__string_end = 36,
  sym_text_token = 37,
  sym_source = 38,
  sym__token = 39,
  sym_code_token = 40,
  sym_fence = 41,
  sym_parse_token = 42,
  sym_inline_parse_token = 43,
  sym_block_parse_token = 44,
  sym_label = 45,
  sym__expression = 46,
  sym_call = 47,
  sym_parenthesised_expression = 48,
  sym_comma_separated_expressions = 49,
  sym_container = 50,
  sym_tuple = 51,
  sym_list = 52,
  sym_set = 53,
  sym_operation = 54,
  sym_unary_operation = 55,
  sym_unary_operator = 56,
  sym_binary_operation = 57,
  sym_binary_operator = 58,
  sym_identifier = 59,
  sym_markdown_token = 60,
  sym_latex_token = 61,
  aux_sym_source_repeat1 = 62,
  aux_sym_code_token_repeat1 = 63,
  aux_sym_comma_separated_expressions_repeat1 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [aux_sym_fence_token1] = "fence_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LF] = "\n",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [aux_sym_binary_operator_token1] = "binary_operator_token1",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_SLASH_SLASH] = "//",
  [anon_sym_SLASH_STAR] = "/*",
  [anon_sym_SLASH_AT] = "/@",
  [sym_literal] = "literal",
  [anon_sym_BQUOTE] = "`",
  [sym_inline_latex_token] = "inline_latex_token",
  [sym_block_latex_token] = "block_latex_token",
  [sym__anyword] = "_anyword",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__string_start] = "_string_start",
  [sym__string_content] = "_string_content",
  [sym__string_end] = "_string_end",
  [sym_text_token] = "text_token",
  [sym_source] = "source",
  [sym__token] = "_token",
  [sym_code_token] = "code_token",
  [sym_fence] = "fence",
  [sym_parse_token] = "parse_token",
  [sym_inline_parse_token] = "inline_parse_token",
  [sym_block_parse_token] = "block_parse_token",
  [sym_label] = "label",
  [sym__expression] = "_expression",
  [sym_call] = "call",
  [sym_parenthesised_expression] = "parenthesised_expression",
  [sym_comma_separated_expressions] = "comma_separated_expressions",
  [sym_container] = "container",
  [sym_tuple] = "tuple",
  [sym_list] = "list",
  [sym_set] = "set",
  [sym_operation] = "operation",
  [sym_unary_operation] = "unary_operation",
  [sym_unary_operator] = "unary_operator",
  [sym_binary_operation] = "binary_operation",
  [sym_binary_operator] = "binary_operator",
  [sym_identifier] = "identifier",
  [sym_markdown_token] = "markdown_token",
  [sym_latex_token] = "latex_token",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_code_token_repeat1] = "code_token_repeat1",
  [aux_sym_comma_separated_expressions_repeat1] = "comma_separated_expressions_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [aux_sym_fence_token1] = aux_sym_fence_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [aux_sym_binary_operator_token1] = aux_sym_binary_operator_token1,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [anon_sym_SLASH_AT] = anon_sym_SLASH_AT,
  [sym_literal] = sym_literal,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym_inline_latex_token] = sym_inline_latex_token,
  [sym_block_latex_token] = sym_block_latex_token,
  [sym__anyword] = sym__anyword,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__string_start] = sym__string_start,
  [sym__string_content] = sym__string_content,
  [sym__string_end] = sym__string_end,
  [sym_text_token] = sym_text_token,
  [sym_source] = sym_source,
  [sym__token] = sym__token,
  [sym_code_token] = sym_code_token,
  [sym_fence] = sym_fence,
  [sym_parse_token] = sym_parse_token,
  [sym_inline_parse_token] = sym_inline_parse_token,
  [sym_block_parse_token] = sym_block_parse_token,
  [sym_label] = sym_label,
  [sym__expression] = sym__expression,
  [sym_call] = sym_call,
  [sym_parenthesised_expression] = sym_parenthesised_expression,
  [sym_comma_separated_expressions] = sym_comma_separated_expressions,
  [sym_container] = sym_container,
  [sym_tuple] = sym_tuple,
  [sym_list] = sym_list,
  [sym_set] = sym_set,
  [sym_operation] = sym_operation,
  [sym_unary_operation] = sym_unary_operation,
  [sym_unary_operator] = sym_unary_operator,
  [sym_binary_operation] = sym_binary_operation,
  [sym_binary_operator] = sym_binary_operator,
  [sym_identifier] = sym_identifier,
  [sym_markdown_token] = sym_markdown_token,
  [sym_latex_token] = sym_latex_token,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_code_token_repeat1] = aux_sym_code_token_repeat1,
  [aux_sym_comma_separated_expressions_repeat1] = aux_sym_comma_separated_expressions_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_fence_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_binary_operator_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_inline_latex_token] = {
    .visible = true,
    .named = true,
  },
  [sym_block_latex_token] = {
    .visible = true,
    .named = true,
  },
  [sym__anyword] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__string_start] = {
    .visible = false,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym__string_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text_token] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_code_token] = {
    .visible = true,
    .named = true,
  },
  [sym_fence] = {
    .visible = true,
    .named = true,
  },
  [sym_parse_token] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_parse_token] = {
    .visible = true,
    .named = true,
  },
  [sym_block_parse_token] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesised_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comma_separated_expressions] = {
    .visible = true,
    .named = true,
  },
  [sym_container] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_token] = {
    .visible = true,
    .named = true,
  },
  [sym_latex_token] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_token_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_separated_expressions_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 53,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 59,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '>') ADVANCE(34);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '`') ADVANCE(49);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '%' ||
          lookahead == '=' ||
          lookahead == '@' ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '|') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '<') ADVANCE(33);
      if (lookahead == '>') ADVANCE(34);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '`') ADVANCE(48);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead == '%' ||
          lookahead == '+' ||
          lookahead == '=' ||
          lookahead == '@' ||
          ('\\' <= lookahead && lookahead <= '^') ||
          lookahead == '|') ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == '[') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 6:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '`') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == '`') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 11:
      if (lookahead == '`') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(3);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '`') ADVANCE(49);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(54);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_fence_token1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_fence_token1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(54);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_binary_operator_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_binary_operator_token1);
      if (lookahead == '*') ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_binary_operator_token1);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == '@') ADVANCE(46);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_binary_operator_token1);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_binary_operator_token1);
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(43);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_binary_operator_token1);
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH_AT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '`') ADVANCE(9);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_inline_latex_token);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_block_latex_token);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__anyword);
      if (lookahead == '`') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__anyword);
      if (lookahead == '`') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__anyword);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 12, .external_lex_state = 2},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 12},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 12},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 12, .external_lex_state = 2},
  [51] = {.lex_state = 12, .external_lex_state = 2},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 12, .external_lex_state = 2},
  [54] = {.lex_state = 12, .external_lex_state = 2},
  [55] = {.lex_state = 12, .external_lex_state = 2},
  [56] = {.lex_state = 12, .external_lex_state = 2},
  [57] = {.lex_state = 12, .external_lex_state = 2},
  [58] = {.lex_state = 12, .external_lex_state = 2},
  [59] = {.lex_state = 12, .external_lex_state = 2},
  [60] = {.lex_state = 12, .external_lex_state = 2},
  [61] = {.lex_state = 12, .external_lex_state = 2},
  [62] = {.lex_state = 12, .external_lex_state = 2},
  [63] = {.lex_state = 12},
  [64] = {.lex_state = 12, .external_lex_state = 2},
  [65] = {.lex_state = 12},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 10},
  [69] = {.lex_state = 10},
  [70] = {.lex_state = 11},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 10},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 10},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
};

enum {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token__string_start = 3,
  ts_external_token__string_content = 4,
  ts_external_token__string_end = 5,
  ts_external_token_text_token = 6,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__string_start] = sym__string_start,
  [ts_external_token__string_content] = sym__string_content,
  [ts_external_token__string_end] = sym__string_end,
  [ts_external_token_text_token] = sym_text_token,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__string_start] = true,
    [ts_external_token__string_content] = true,
    [ts_external_token__string_end] = true,
    [ts_external_token_text_token] = true,
  },
  [2] = {
    [ts_external_token_text_token] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [aux_sym_fence_token1] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [aux_sym_binary_operator_token1] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(1),
    [anon_sym_SLASH_AT] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__string_start] = ACTIONS(1),
    [sym__string_content] = ACTIONS(1),
    [sym__string_end] = ACTIONS(1),
    [sym_text_token] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(79),
    [sym__token] = STATE(50),
    [sym_code_token] = STATE(50),
    [sym_fence] = STATE(68),
    [sym_parse_token] = STATE(50),
    [sym_inline_parse_token] = STATE(64),
    [sym_block_parse_token] = STATE(64),
    [sym_markdown_token] = STATE(50),
    [sym_latex_token] = STATE(50),
    [aux_sym_source_repeat1] = STATE(50),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_BQUOTE] = ACTIONS(9),
    [sym_inline_latex_token] = ACTIONS(11),
    [sym_block_latex_token] = ACTIONS(11),
    [sym_text_token] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    STATE(76), 1,
      sym_comma_separated_expressions,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(6), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [46] = 12,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    STATE(81), 1,
      sym_comma_separated_expressions,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(6), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [92] = 13,
    ACTIONS(29), 1,
      aux_sym_fence_token1,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(33), 1,
      anon_sym_LF,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      sym_literal,
    STATE(17), 1,
      sym_label,
    STATE(37), 1,
      sym_unary_operator,
    STATE(49), 1,
      sym_identifier,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(46), 5,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
  [140] = 12,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(27), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    STATE(80), 1,
      sym_comma_separated_expressions,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(6), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [186] = 9,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    ACTIONS(53), 1,
      aux_sym_binary_operator_token1,
    STATE(21), 1,
      sym_binary_operator,
    STATE(67), 1,
      aux_sym_comma_separated_expressions_repeat1,
    ACTIONS(45), 3,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    ACTIONS(55), 11,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [226] = 11,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_RPAREN,
    ACTIONS(59), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(8), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [269] = 7,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      aux_sym_binary_operator_token1,
    STATE(21), 1,
      sym_binary_operator,
    ACTIONS(61), 4,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
    ACTIONS(55), 11,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [304] = 3,
    ACTIONS(65), 1,
      aux_sym_binary_operator_token1,
    STATE(21), 1,
      sym_binary_operator,
    ACTIONS(63), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [331] = 11,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      sym_literal,
    ACTIONS(67), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(8), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [374] = 2,
    ACTIONS(71), 2,
      anon_sym_COLON,
      aux_sym_binary_operator_token1,
    ACTIONS(69), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [399] = 11,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(75), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(29), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [442] = 11,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      sym_literal,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(8), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [485] = 11,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    ACTIONS(81), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(32), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [528] = 11,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
    ACTIONS(85), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(34), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [571] = 3,
    ACTIONS(89), 1,
      aux_sym_binary_operator_token1,
    STATE(21), 1,
      sym_binary_operator,
    ACTIONS(87), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [598] = 11,
    ACTIONS(29), 1,
      aux_sym_fence_token1,
    ACTIONS(31), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LF,
    ACTIONS(93), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(39), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(47), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [641] = 11,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      sym_literal,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(8), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [684] = 11,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      sym_literal,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(8), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [727] = 11,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      sym_literal,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(8), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [770] = 10,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(101), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(9), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [810] = 2,
    ACTIONS(105), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(103), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [834] = 2,
    ACTIONS(109), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(107), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [858] = 10,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(111), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(48), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [898] = 2,
    ACTIONS(115), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(113), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [922] = 2,
    ACTIONS(119), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(117), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [946] = 2,
    ACTIONS(123), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(121), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [970] = 2,
    ACTIONS(127), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(125), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [994] = 9,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      sym_binary_operator,
    STATE(71), 1,
      aux_sym_comma_separated_expressions_repeat1,
    ACTIONS(55), 11,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1032] = 2,
    ACTIONS(135), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(133), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1056] = 2,
    ACTIONS(139), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(137), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1080] = 9,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      sym_binary_operator,
    STATE(73), 1,
      aux_sym_comma_separated_expressions_repeat1,
    ACTIONS(55), 11,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1118] = 2,
    ACTIONS(147), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(145), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1142] = 9,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(149), 1,
      anon_sym_RBRACK,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      sym_binary_operator,
    STATE(74), 1,
      aux_sym_comma_separated_expressions_repeat1,
    ACTIONS(55), 11,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1180] = 10,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(153), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(45), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [1220] = 2,
    ACTIONS(157), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(155), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1244] = 10,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(16), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [1284] = 2,
    ACTIONS(163), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(161), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1308] = 2,
    ACTIONS(167), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(165), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1332] = 2,
    ACTIONS(171), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(169), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1356] = 2,
    ACTIONS(175), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(173), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1380] = 2,
    ACTIONS(179), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(177), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1404] = 2,
    ACTIONS(183), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(181), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1428] = 10,
    ACTIONS(15), 1,
      aux_sym_fence_token1,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      sym_literal,
    STATE(37), 1,
      sym_unary_operator,
    ACTIONS(25), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(39), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(41), 3,
      sym_tuple,
      sym_list,
      sym_set,
    STATE(8), 6,
      sym__expression,
      sym_call,
      sym_parenthesised_expression,
      sym_container,
      sym_operation,
      sym_identifier,
  [1468] = 7,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_binary_operator,
    ACTIONS(55), 11,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1500] = 7,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_binary_operator,
    ACTIONS(55), 11,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1532] = 7,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_binary_operator,
    ACTIONS(55), 11,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1564] = 7,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_binary_operator,
    ACTIONS(55), 11,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1596] = 3,
    ACTIONS(195), 1,
      anon_sym_COLON,
    ACTIONS(197), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(193), 15,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_STAR_STAR,
      anon_sym_COLON_EQ,
      anon_sym_DASH_GT,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_SLASH_SLASH,
      anon_sym_SLASH_STAR,
      anon_sym_SLASH_AT,
  [1620] = 9,
    ACTIONS(5), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_BQUOTE,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    ACTIONS(201), 1,
      sym_text_token,
    STATE(68), 1,
      sym_fence,
    ACTIONS(11), 2,
      sym_inline_latex_token,
      sym_block_latex_token,
    STATE(64), 2,
      sym_inline_parse_token,
      sym_block_parse_token,
    STATE(51), 6,
      sym__token,
      sym_code_token,
      sym_parse_token,
      sym_markdown_token,
      sym_latex_token,
      aux_sym_source_repeat1,
  [1655] = 9,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    ACTIONS(211), 1,
      anon_sym_BQUOTE,
    ACTIONS(217), 1,
      sym_text_token,
    STATE(68), 1,
      sym_fence,
    ACTIONS(214), 2,
      sym_inline_latex_token,
      sym_block_latex_token,
    STATE(64), 2,
      sym_inline_parse_token,
      sym_block_parse_token,
    STATE(51), 6,
      sym__token,
      sym_code_token,
      sym_parse_token,
      sym_markdown_token,
      sym_latex_token,
      aux_sym_source_repeat1,
  [1690] = 2,
    ACTIONS(222), 1,
      anon_sym_LF,
    ACTIONS(220), 7,
      aux_sym_fence_token1,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_literal,
  [1703] = 3,
    ACTIONS(226), 1,
      aux_sym_fence_token1,
    ACTIONS(228), 1,
      anon_sym_BQUOTE,
    ACTIONS(224), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1718] = 2,
    ACTIONS(232), 1,
      anon_sym_BQUOTE,
    ACTIONS(230), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1730] = 2,
    ACTIONS(236), 1,
      anon_sym_BQUOTE,
    ACTIONS(234), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1742] = 2,
    ACTIONS(240), 1,
      anon_sym_BQUOTE,
    ACTIONS(238), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1754] = 2,
    ACTIONS(244), 1,
      anon_sym_BQUOTE,
    ACTIONS(242), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1766] = 2,
    ACTIONS(248), 1,
      anon_sym_BQUOTE,
    ACTIONS(246), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1778] = 2,
    ACTIONS(252), 1,
      anon_sym_BQUOTE,
    ACTIONS(250), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1790] = 2,
    ACTIONS(256), 1,
      anon_sym_BQUOTE,
    ACTIONS(254), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1802] = 2,
    ACTIONS(260), 1,
      anon_sym_BQUOTE,
    ACTIONS(258), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1814] = 2,
    ACTIONS(264), 1,
      anon_sym_BQUOTE,
    ACTIONS(262), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1826] = 1,
    ACTIONS(266), 7,
      aux_sym_fence_token1,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_literal,
  [1836] = 2,
    ACTIONS(270), 1,
      anon_sym_BQUOTE,
    ACTIONS(268), 6,
      sym_text_token,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_LBRACE,
      sym_inline_latex_token,
      sym_block_latex_token,
  [1848] = 1,
    ACTIONS(272), 7,
      aux_sym_fence_token1,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_literal,
  [1858] = 3,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_comma_separated_expressions_repeat1,
    ACTIONS(61), 3,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1870] = 3,
    ACTIONS(51), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_comma_separated_expressions_repeat1,
    ACTIONS(277), 3,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1882] = 4,
    ACTIONS(279), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(281), 1,
      sym__anyword,
    STATE(62), 1,
      sym_fence,
    STATE(69), 1,
      aux_sym_code_token_repeat1,
  [1895] = 4,
    ACTIONS(279), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(283), 1,
      sym__anyword,
    STATE(57), 1,
      sym_fence,
    STATE(72), 1,
      aux_sym_code_token_repeat1,
  [1908] = 2,
    ACTIONS(285), 1,
      aux_sym_fence_token1,
    ACTIONS(228), 2,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym__anyword,
  [1916] = 3,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_comma_separated_expressions_repeat1,
  [1926] = 3,
    ACTIONS(289), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(291), 1,
      sym__anyword,
    STATE(72), 1,
      aux_sym_code_token_repeat1,
  [1936] = 3,
    ACTIONS(57), 1,
      anon_sym_RPAREN,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_comma_separated_expressions_repeat1,
  [1946] = 3,
    ACTIONS(67), 1,
      anon_sym_RBRACK,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_comma_separated_expressions_repeat1,
  [1956] = 1,
    ACTIONS(252), 2,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym__anyword,
  [1961] = 1,
    ACTIONS(298), 1,
      anon_sym_RBRACE,
  [1965] = 1,
    ACTIONS(300), 1,
      sym_text_token,
  [1969] = 1,
    ACTIONS(302), 1,
      anon_sym_BQUOTE,
  [1973] = 1,
    ACTIONS(304), 1,
      ts_builtin_sym_end,
  [1977] = 1,
    ACTIONS(298), 1,
      anon_sym_RBRACK,
  [1981] = 1,
    ACTIONS(298), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 92,
  [SMALL_STATE(5)] = 140,
  [SMALL_STATE(6)] = 186,
  [SMALL_STATE(7)] = 226,
  [SMALL_STATE(8)] = 269,
  [SMALL_STATE(9)] = 304,
  [SMALL_STATE(10)] = 331,
  [SMALL_STATE(11)] = 374,
  [SMALL_STATE(12)] = 399,
  [SMALL_STATE(13)] = 442,
  [SMALL_STATE(14)] = 485,
  [SMALL_STATE(15)] = 528,
  [SMALL_STATE(16)] = 571,
  [SMALL_STATE(17)] = 598,
  [SMALL_STATE(18)] = 641,
  [SMALL_STATE(19)] = 684,
  [SMALL_STATE(20)] = 727,
  [SMALL_STATE(21)] = 770,
  [SMALL_STATE(22)] = 810,
  [SMALL_STATE(23)] = 834,
  [SMALL_STATE(24)] = 858,
  [SMALL_STATE(25)] = 898,
  [SMALL_STATE(26)] = 922,
  [SMALL_STATE(27)] = 946,
  [SMALL_STATE(28)] = 970,
  [SMALL_STATE(29)] = 994,
  [SMALL_STATE(30)] = 1032,
  [SMALL_STATE(31)] = 1056,
  [SMALL_STATE(32)] = 1080,
  [SMALL_STATE(33)] = 1118,
  [SMALL_STATE(34)] = 1142,
  [SMALL_STATE(35)] = 1180,
  [SMALL_STATE(36)] = 1220,
  [SMALL_STATE(37)] = 1244,
  [SMALL_STATE(38)] = 1284,
  [SMALL_STATE(39)] = 1308,
  [SMALL_STATE(40)] = 1332,
  [SMALL_STATE(41)] = 1356,
  [SMALL_STATE(42)] = 1380,
  [SMALL_STATE(43)] = 1404,
  [SMALL_STATE(44)] = 1428,
  [SMALL_STATE(45)] = 1468,
  [SMALL_STATE(46)] = 1500,
  [SMALL_STATE(47)] = 1532,
  [SMALL_STATE(48)] = 1564,
  [SMALL_STATE(49)] = 1596,
  [SMALL_STATE(50)] = 1620,
  [SMALL_STATE(51)] = 1655,
  [SMALL_STATE(52)] = 1690,
  [SMALL_STATE(53)] = 1703,
  [SMALL_STATE(54)] = 1718,
  [SMALL_STATE(55)] = 1730,
  [SMALL_STATE(56)] = 1742,
  [SMALL_STATE(57)] = 1754,
  [SMALL_STATE(58)] = 1766,
  [SMALL_STATE(59)] = 1778,
  [SMALL_STATE(60)] = 1790,
  [SMALL_STATE(61)] = 1802,
  [SMALL_STATE(62)] = 1814,
  [SMALL_STATE(63)] = 1826,
  [SMALL_STATE(64)] = 1836,
  [SMALL_STATE(65)] = 1848,
  [SMALL_STATE(66)] = 1858,
  [SMALL_STATE(67)] = 1870,
  [SMALL_STATE(68)] = 1882,
  [SMALL_STATE(69)] = 1895,
  [SMALL_STATE(70)] = 1908,
  [SMALL_STATE(71)] = 1916,
  [SMALL_STATE(72)] = 1926,
  [SMALL_STATE(73)] = 1936,
  [SMALL_STATE(74)] = 1946,
  [SMALL_STATE(75)] = 1956,
  [SMALL_STATE(76)] = 1961,
  [SMALL_STATE(77)] = 1965,
  [SMALL_STATE(78)] = 1969,
  [SMALL_STATE(79)] = 1973,
  [SMALL_STATE(80)] = 1977,
  [SMALL_STATE(81)] = 1981,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_separated_expressions, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_separated_expressions_repeat1, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operation, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operation, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operation, 2),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operation, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 5),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 5),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesised_expression, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesised_expression, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 2),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple, 2),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tuple, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 4),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 5),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 5),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 1),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation, 1),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_container, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_container, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(70),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(4),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(77),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(55),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(51),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label, 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence, 1),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_parse_token, 3),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_parse_token, 3),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_latex_token, 1),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_latex_token, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_token, 3),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_token, 3),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_token, 3),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_token, 3),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_parse_token, 4),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_parse_token, 4),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence, 2),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_parse_token, 4),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_parse_token, 4),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_parse_token, 5),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_parse_token, 5),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_token, 2),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_token, 2),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parse_token, 1),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parse_token, 1),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operator, 1),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_separated_expressions_repeat1, 2), SHIFT_REPEAT(44),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_separated_expressions, 2),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_token_repeat1, 2),
  [291] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_token_repeat1, 2), SHIFT_REPEAT(72),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [304] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_mson_external_scanner_create(void);
void tree_sitter_mson_external_scanner_destroy(void *);
bool tree_sitter_mson_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_mson_external_scanner_serialize(void *, char *);
void tree_sitter_mson_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_mson(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_mson_external_scanner_create,
      tree_sitter_mson_external_scanner_destroy,
      tree_sitter_mson_external_scanner_scan,
      tree_sitter_mson_external_scanner_serialize,
      tree_sitter_mson_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
