#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 156
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 72
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 1,
  sym_fence_tag = 2,
  anon_sym_STAR = 3,
  anon_sym__ = 4,
  anon_sym_STAR_STAR = 5,
  anon_sym___ = 6,
  anon_sym_STAR_STAR_STAR = 7,
  anon_sym____ = 8,
  anon_sym_TILDE_TILDE = 9,
  aux_sym_markdown_token_token1 = 10,
  aux_sym_markdown_token_token2 = 11,
  sym__text_word = 12,
  sym__text_punctuation = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_COMMA = 16,
  anon_sym_LPAREN = 17,
  anon_sym_RPAREN = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  anon_sym_DASH = 21,
  anon_sym_PLUS = 22,
  aux_sym_binary_operator_token1 = 23,
  anon_sym_BANG_EQ = 24,
  anon_sym_GT_EQ = 25,
  anon_sym_LT_EQ = 26,
  sym_identifier = 27,
  sym_literal = 28,
  sym_inline_latex_math = 29,
  sym_block_latex_math = 30,
  aux_sym__anyline_token1 = 31,
  sym__w = 32,
  sym__iw = 33,
  sym__linebreak = 34,
  sym_source = 35,
  sym__block = 36,
  sym_code = 37,
  sym_fence = 38,
  sym__text_line = 39,
  sym__text_inline = 40,
  sym__first_text_token = 41,
  sym_plain_text_inline = 42,
  sym__text_token = 43,
  sym_markdown_token = 44,
  sym__text_separator = 45,
  sym_parse_token = 46,
  sym_inline_parse = 47,
  sym_block_parse = 48,
  sym_explicit_inline_parse = 49,
  sym_explicit_block_parse = 50,
  sym_wcommaw = 51,
  sym_wcomma = 52,
  sym_comma_separated_expressions = 53,
  sym_container = 54,
  sym_call = 55,
  sym_operation = 56,
  sym_unary_operator = 57,
  sym_binary_operator = 58,
  sym_unary_operation = 59,
  sym_binary_operation = 60,
  sym__wexpressionw = 61,
  sym_expression = 62,
  sym__atom = 63,
  sym_latex_math = 64,
  sym__anyline = 65,
  sym__lineend = 66,
  aux_sym_source_repeat1 = 67,
  aux_sym_code_repeat1 = 68,
  aux_sym__text_inline_repeat1 = 69,
  aux_sym_plain_text_inline_repeat1 = 70,
  aux_sym_comma_separated_expressions_repeat1 = 71,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [sym_fence_tag] = "fence_tag",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym___] = "__",
  [anon_sym_STAR_STAR_STAR] = "***",
  [anon_sym____] = "___",
  [anon_sym_TILDE_TILDE] = "~~",
  [aux_sym_markdown_token_token1] = "markdown_token_token1",
  [aux_sym_markdown_token_token2] = "markdown_token_token2",
  [sym__text_word] = "_text_word",
  [sym__text_punctuation] = "_text_punctuation",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [aux_sym_binary_operator_token1] = "binary_operator_token1",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [sym_identifier] = "identifier",
  [sym_literal] = "literal",
  [sym_inline_latex_math] = "inline_latex_math",
  [sym_block_latex_math] = "block_latex_math",
  [aux_sym__anyline_token1] = "_anyline_token1",
  [sym__w] = "_w",
  [sym__iw] = "_iw",
  [sym__linebreak] = "_linebreak",
  [sym_source] = "source",
  [sym__block] = "_block",
  [sym_code] = "code",
  [sym_fence] = "fence",
  [sym__text_line] = "_text_line",
  [sym__text_inline] = "_text_inline",
  [sym__first_text_token] = "_first_text_token",
  [sym_plain_text_inline] = "plain_text_inline",
  [sym__text_token] = "_text_token",
  [sym_markdown_token] = "markdown_token",
  [sym__text_separator] = "_text_separator",
  [sym_parse_token] = "parse_token",
  [sym_inline_parse] = "inline_parse",
  [sym_block_parse] = "block_parse",
  [sym_explicit_inline_parse] = "explicit_inline_parse",
  [sym_explicit_block_parse] = "explicit_block_parse",
  [sym_wcommaw] = "wcommaw",
  [sym_wcomma] = "wcomma",
  [sym_comma_separated_expressions] = "comma_separated_expressions",
  [sym_container] = "container",
  [sym_call] = "call",
  [sym_operation] = "operation",
  [sym_unary_operator] = "unary_operator",
  [sym_binary_operator] = "binary_operator",
  [sym_unary_operation] = "unary_operation",
  [sym_binary_operation] = "binary_operation",
  [sym__wexpressionw] = "_wexpressionw",
  [sym_expression] = "expression",
  [sym__atom] = "_atom",
  [sym_latex_math] = "latex_math",
  [sym__anyline] = "_anyline",
  [sym__lineend] = "_lineend",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
  [aux_sym__text_inline_repeat1] = "_text_inline_repeat1",
  [aux_sym_plain_text_inline_repeat1] = "plain_text_inline_repeat1",
  [aux_sym_comma_separated_expressions_repeat1] = "comma_separated_expressions_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [sym_fence_tag] = sym_fence_tag,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym___] = anon_sym___,
  [anon_sym_STAR_STAR_STAR] = anon_sym_STAR_STAR_STAR,
  [anon_sym____] = anon_sym____,
  [anon_sym_TILDE_TILDE] = anon_sym_TILDE_TILDE,
  [aux_sym_markdown_token_token1] = aux_sym_markdown_token_token1,
  [aux_sym_markdown_token_token2] = aux_sym_markdown_token_token2,
  [sym__text_word] = sym__text_word,
  [sym__text_punctuation] = sym__text_punctuation,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [aux_sym_binary_operator_token1] = aux_sym_binary_operator_token1,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [sym_identifier] = sym_identifier,
  [sym_literal] = sym_literal,
  [sym_inline_latex_math] = sym_inline_latex_math,
  [sym_block_latex_math] = sym_block_latex_math,
  [aux_sym__anyline_token1] = aux_sym__anyline_token1,
  [sym__w] = sym__w,
  [sym__iw] = sym__iw,
  [sym__linebreak] = sym__linebreak,
  [sym_source] = sym_source,
  [sym__block] = sym__block,
  [sym_code] = sym_code,
  [sym_fence] = sym_fence,
  [sym__text_line] = sym__text_line,
  [sym__text_inline] = sym__text_inline,
  [sym__first_text_token] = sym__first_text_token,
  [sym_plain_text_inline] = sym_plain_text_inline,
  [sym__text_token] = sym__text_token,
  [sym_markdown_token] = sym_markdown_token,
  [sym__text_separator] = sym__text_separator,
  [sym_parse_token] = sym_parse_token,
  [sym_inline_parse] = sym_inline_parse,
  [sym_block_parse] = sym_block_parse,
  [sym_explicit_inline_parse] = sym_explicit_inline_parse,
  [sym_explicit_block_parse] = sym_explicit_block_parse,
  [sym_wcommaw] = sym_wcommaw,
  [sym_wcomma] = sym_wcomma,
  [sym_comma_separated_expressions] = sym_comma_separated_expressions,
  [sym_container] = sym_container,
  [sym_call] = sym_call,
  [sym_operation] = sym_operation,
  [sym_unary_operator] = sym_unary_operator,
  [sym_binary_operator] = sym_binary_operator,
  [sym_unary_operation] = sym_unary_operation,
  [sym_binary_operation] = sym_binary_operation,
  [sym__wexpressionw] = sym__wexpressionw,
  [sym_expression] = sym_expression,
  [sym__atom] = sym__atom,
  [sym_latex_math] = sym_latex_math,
  [sym__anyline] = sym__anyline,
  [sym__lineend] = sym__lineend,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
  [aux_sym__text_inline_repeat1] = aux_sym__text_inline_repeat1,
  [aux_sym_plain_text_inline_repeat1] = aux_sym_plain_text_inline_repeat1,
  [aux_sym_comma_separated_expressions_repeat1] = aux_sym_comma_separated_expressions_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_fence_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym____] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_TILDE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_markdown_token_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markdown_token_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__text_word] = {
    .visible = false,
    .named = true,
  },
  [sym__text_punctuation] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_binary_operator_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_latex_math] = {
    .visible = true,
    .named = true,
  },
  [sym_block_latex_math] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__anyline_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__w] = {
    .visible = false,
    .named = true,
  },
  [sym__iw] = {
    .visible = false,
    .named = true,
  },
  [sym__linebreak] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_fence] = {
    .visible = true,
    .named = true,
  },
  [sym__text_line] = {
    .visible = false,
    .named = true,
  },
  [sym__text_inline] = {
    .visible = false,
    .named = true,
  },
  [sym__first_text_token] = {
    .visible = false,
    .named = true,
  },
  [sym_plain_text_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__text_token] = {
    .visible = false,
    .named = true,
  },
  [sym_markdown_token] = {
    .visible = true,
    .named = true,
  },
  [sym__text_separator] = {
    .visible = false,
    .named = true,
  },
  [sym_parse_token] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_parse] = {
    .visible = true,
    .named = true,
  },
  [sym_block_parse] = {
    .visible = true,
    .named = true,
  },
  [sym_explicit_inline_parse] = {
    .visible = true,
    .named = true,
  },
  [sym_explicit_block_parse] = {
    .visible = true,
    .named = true,
  },
  [sym_wcommaw] = {
    .visible = true,
    .named = true,
  },
  [sym_wcomma] = {
    .visible = true,
    .named = true,
  },
  [sym_comma_separated_expressions] = {
    .visible = true,
    .named = true,
  },
  [sym_container] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operation] = {
    .visible = true,
    .named = true,
  },
  [sym__wexpressionw] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_latex_math] = {
    .visible = true,
    .named = true,
  },
  [sym__anyline] = {
    .visible = false,
    .named = true,
  },
  [sym__lineend] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__text_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_plain_text_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_separated_expressions_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == ' ') ADVANCE(61);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '+') ADVANCE(47);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead == '[') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(45);
      if (lookahead == '_') ADVANCE(28);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '~') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(62);
      if (lookahead == '.' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '?') ADVANCE(37);
      if (lookahead == '%' ||
          lookahead == '/' ||
          ('=' <= lookahead && lookahead <= '@') ||
          lookahead == '^' ||
          lookahead == '|') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == ' ') ADVANCE(61);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead == '[') ADVANCE(44);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(62);
      if (lookahead == '%' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '@' ||
          lookahead == '^' ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == '+') ADVANCE(47);
      if (lookahead == '-') ADVANCE(46);
      if ((',' <= lookahead && lookahead <= '.') ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '?') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == ' ') ADVANCE(63);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '`') ADVANCE(59);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(61);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == ',') ADVANCE(40);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead == '[') ADVANCE(44);
      if (lookahead == ']') ADVANCE(45);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') ADVANCE(62);
      if (lookahead == '%' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          lookahead == '=' ||
          lookahead == '@' ||
          lookahead == '^' ||
          lookahead == '|') ADVANCE(48);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(42);
      if (lookahead == ')') ADVANCE(43);
      if (lookahead == '+') ADVANCE(47);
      if (lookahead == ',') ADVANCE(40);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 7:
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == '[') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == '(') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == ')') ADVANCE(56);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == ')') ADVANCE(35);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == ']') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == ']') ADVANCE(8);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '`') ADVANCE(17);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == '`') ADVANCE(24);
      END_STATE();
    case 18:
      if (lookahead == '`') ADVANCE(34);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '~') ADVANCE(33);
      END_STATE();
    case 20:
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(10);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(15);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == ' ') ADVANCE(63);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == ',') ADVANCE(40);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '_') ADVANCE(28);
      if (lookahead == '`') ADVANCE(16);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '~') ADVANCE(19);
      if (lookahead == '"' ||
          lookahead == '#' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_fence_tag);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '_') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      if (lookahead == '*') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym___);
      if (lookahead == '_') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR_STAR_STAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym____);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_TILDE_TILDE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_markdown_token_token1);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_markdown_token_token2);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__text_word);
      if (lookahead == '"' ||
          lookahead == '#' ||
          ('\'' <= lookahead && lookahead <= ')') ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__text_punctuation);
      if (lookahead == ',' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '?') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead == ',' ||
          lookahead == '.' ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '?') ADVANCE(37);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_binary_operator_token1);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_binary_operator_token1);
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_binary_operator_token1);
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_inline_latex_math);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_block_latex_math);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym__anyline_token1);
      if (lookahead == '`') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__anyline_token1);
      if (lookahead == '`') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym__anyline_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__w);
      if (lookahead == ' ') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__w);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__iw);
      if (lookahead == ' ') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__linebreak);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__linebreak);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 22},
  [4] = {.lex_state = 22},
  [5] = {.lex_state = 22},
  [6] = {.lex_state = 22},
  [7] = {.lex_state = 22},
  [8] = {.lex_state = 22},
  [9] = {.lex_state = 22},
  [10] = {.lex_state = 22},
  [11] = {.lex_state = 22},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 22},
  [65] = {.lex_state = 22},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 22},
  [71] = {.lex_state = 22},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 4},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 6},
  [83] = {.lex_state = 6},
  [84] = {.lex_state = 6},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 6},
  [91] = {.lex_state = 22},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 22},
  [94] = {.lex_state = 22},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 4},
  [99] = {.lex_state = 22},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 4},
  [102] = {.lex_state = 4},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 22},
  [110] = {.lex_state = 2},
  [111] = {.lex_state = 4},
  [112] = {.lex_state = 2},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 22},
  [115] = {.lex_state = 22},
  [116] = {.lex_state = 22},
  [117] = {.lex_state = 22},
  [118] = {.lex_state = 22},
  [119] = {.lex_state = 22},
  [120] = {.lex_state = 22},
  [121] = {.lex_state = 22},
  [122] = {.lex_state = 22},
  [123] = {.lex_state = 22},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 22},
  [127] = {.lex_state = 22},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 22},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 22},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 22},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 22},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 22},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 22},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 22},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 22},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 22},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [sym_fence_tag] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [anon_sym_STAR_STAR_STAR] = ACTIONS(1),
    [anon_sym____] = ACTIONS(1),
    [anon_sym_TILDE_TILDE] = ACTIONS(1),
    [aux_sym_markdown_token_token1] = ACTIONS(1),
    [sym__text_punctuation] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [aux_sym_binary_operator_token1] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [sym_inline_latex_math] = ACTIONS(1),
    [sym_block_latex_math] = ACTIONS(1),
    [sym__w] = ACTIONS(1),
    [sym__iw] = ACTIONS(1),
    [sym__linebreak] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(124),
    [sym__block] = STATE(2),
    [sym_code] = STATE(2),
    [sym_fence] = STATE(79),
    [sym__text_line] = STATE(2),
    [sym__text_inline] = STATE(134),
    [sym__first_text_token] = STATE(93),
    [sym__text_token] = STATE(93),
    [sym_markdown_token] = STATE(103),
    [sym_parse_token] = STATE(103),
    [sym_inline_parse] = STATE(105),
    [sym_block_parse] = STATE(105),
    [sym_explicit_inline_parse] = STATE(106),
    [sym_explicit_block_parse] = STATE(107),
    [sym_latex_math] = STATE(103),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym__] = ACTIONS(9),
    [anon_sym_STAR_STAR] = ACTIONS(11),
    [anon_sym___] = ACTIONS(13),
    [anon_sym_STAR_STAR_STAR] = ACTIONS(15),
    [anon_sym____] = ACTIONS(17),
    [anon_sym_TILDE_TILDE] = ACTIONS(19),
    [aux_sym_markdown_token_token1] = ACTIONS(21),
    [aux_sym_markdown_token_token2] = ACTIONS(21),
    [sym__text_word] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
    [sym_inline_latex_math] = ACTIONS(27),
    [sym_block_latex_math] = ACTIONS(27),
    [sym__iw] = ACTIONS(29),
    [sym__linebreak] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 23,
    ACTIONS(5), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(7), 1,
      anon_sym_STAR,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      anon_sym_STAR_STAR,
    ACTIONS(13), 1,
      anon_sym___,
    ACTIONS(15), 1,
      anon_sym_STAR_STAR_STAR,
    ACTIONS(17), 1,
      anon_sym____,
    ACTIONS(19), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(23), 1,
      sym__text_word,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      sym__iw,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      sym__linebreak,
    STATE(79), 1,
      sym_fence,
    STATE(106), 1,
      sym_explicit_inline_parse,
    STATE(107), 1,
      sym_explicit_block_parse,
    STATE(134), 1,
      sym__text_inline,
    ACTIONS(21), 2,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
    ACTIONS(27), 2,
      sym_inline_latex_math,
      sym_block_latex_math,
    STATE(93), 2,
      sym__first_text_token,
      sym__text_token,
    STATE(105), 2,
      sym_inline_parse,
      sym_block_parse,
    STATE(103), 3,
      sym_markdown_token,
      sym_parse_token,
      sym_latex_math,
    STATE(3), 4,
      sym__block,
      sym_code,
      sym__text_line,
      aux_sym_source_repeat1,
  [79] = 23,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(42), 1,
      anon_sym_STAR,
    ACTIONS(45), 1,
      anon_sym__,
    ACTIONS(48), 1,
      anon_sym_STAR_STAR,
    ACTIONS(51), 1,
      anon_sym___,
    ACTIONS(54), 1,
      anon_sym_STAR_STAR_STAR,
    ACTIONS(57), 1,
      anon_sym____,
    ACTIONS(60), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(66), 1,
      sym__text_word,
    ACTIONS(69), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      sym__iw,
    ACTIONS(78), 1,
      sym__linebreak,
    STATE(79), 1,
      sym_fence,
    STATE(106), 1,
      sym_explicit_inline_parse,
    STATE(107), 1,
      sym_explicit_block_parse,
    STATE(134), 1,
      sym__text_inline,
    ACTIONS(63), 2,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
    ACTIONS(72), 2,
      sym_inline_latex_math,
      sym_block_latex_math,
    STATE(93), 2,
      sym__first_text_token,
      sym__text_token,
    STATE(105), 2,
      sym_inline_parse,
      sym_block_parse,
    STATE(103), 3,
      sym_markdown_token,
      sym_parse_token,
      sym_latex_math,
    STATE(3), 4,
      sym__block,
      sym_code,
      sym__text_line,
      aux_sym_source_repeat1,
  [158] = 16,
    ACTIONS(7), 1,
      anon_sym_STAR,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      anon_sym_STAR_STAR,
    ACTIONS(13), 1,
      anon_sym___,
    ACTIONS(15), 1,
      anon_sym_STAR_STAR_STAR,
    ACTIONS(17), 1,
      anon_sym____,
    ACTIONS(19), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(23), 1,
      sym__text_word,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    STATE(106), 1,
      sym_explicit_inline_parse,
    STATE(107), 1,
      sym_explicit_block_parse,
    STATE(121), 1,
      sym__text_token,
    ACTIONS(21), 2,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
    ACTIONS(27), 2,
      sym_inline_latex_math,
      sym_block_latex_math,
    STATE(105), 2,
      sym_inline_parse,
      sym_block_parse,
    STATE(103), 3,
      sym_markdown_token,
      sym_parse_token,
      sym_latex_math,
  [212] = 16,
    ACTIONS(7), 1,
      anon_sym_STAR,
    ACTIONS(9), 1,
      anon_sym__,
    ACTIONS(11), 1,
      anon_sym_STAR_STAR,
    ACTIONS(13), 1,
      anon_sym___,
    ACTIONS(15), 1,
      anon_sym_STAR_STAR_STAR,
    ACTIONS(17), 1,
      anon_sym____,
    ACTIONS(19), 1,
      anon_sym_TILDE_TILDE,
    ACTIONS(23), 1,
      sym__text_word,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    STATE(106), 1,
      sym_explicit_inline_parse,
    STATE(107), 1,
      sym_explicit_block_parse,
    STATE(115), 1,
      sym__text_token,
    ACTIONS(21), 2,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
    ACTIONS(27), 2,
      sym_inline_latex_math,
      sym_block_latex_math,
    STATE(105), 2,
      sym_inline_parse,
      sym_block_parse,
    STATE(103), 3,
      sym_markdown_token,
      sym_parse_token,
      sym_latex_math,
  [266] = 2,
    ACTIONS(83), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
    ACTIONS(81), 13,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
      sym__text_word,
      anon_sym_LBRACE,
      sym_inline_latex_math,
      sym_block_latex_math,
      sym__iw,
      sym__linebreak,
  [288] = 2,
    ACTIONS(87), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
    ACTIONS(85), 13,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
      sym__text_word,
      anon_sym_LBRACE,
      sym_inline_latex_math,
      sym_block_latex_math,
      sym__iw,
      sym__linebreak,
  [310] = 2,
    ACTIONS(91), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
    ACTIONS(89), 13,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
      sym__text_word,
      anon_sym_LBRACE,
      sym_inline_latex_math,
      sym_block_latex_math,
      sym__iw,
      sym__linebreak,
  [332] = 2,
    ACTIONS(95), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
    ACTIONS(93), 13,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
      sym__text_word,
      anon_sym_LBRACE,
      sym_inline_latex_math,
      sym_block_latex_math,
      sym__iw,
      sym__linebreak,
  [354] = 2,
    ACTIONS(99), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
    ACTIONS(97), 13,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
      sym__text_word,
      anon_sym_LBRACE,
      sym_inline_latex_math,
      sym_block_latex_math,
      sym__iw,
      sym__linebreak,
  [376] = 2,
    ACTIONS(103), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
    ACTIONS(101), 13,
      ts_builtin_sym_end,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      aux_sym_markdown_token_token1,
      aux_sym_markdown_token_token2,
      sym__text_word,
      anon_sym_LBRACE,
      sym_inline_latex_math,
      sym_block_latex_math,
      sym__iw,
      sym__linebreak,
  [398] = 10,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(111), 1,
      sym__iw,
    ACTIONS(113), 1,
      sym__linebreak,
    STATE(34), 1,
      sym__lineend,
    STATE(36), 1,
      sym_unary_operator,
    STATE(62), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [435] = 9,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      sym__w,
    STATE(21), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    STATE(154), 1,
      sym_comma_separated_expressions,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [469] = 9,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      sym__w,
    STATE(36), 1,
      sym_unary_operator,
    STATE(52), 1,
      sym_expression,
    STATE(142), 1,
      sym__wexpressionw,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [503] = 9,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      sym__w,
    STATE(36), 1,
      sym_unary_operator,
    STATE(52), 1,
      sym_expression,
    STATE(125), 1,
      sym__wexpressionw,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [537] = 9,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      sym__w,
    STATE(36), 1,
      sym_unary_operator,
    STATE(52), 1,
      sym_expression,
    STATE(145), 1,
      sym__wexpressionw,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [571] = 9,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      sym__w,
    STATE(36), 1,
      sym_unary_operator,
    STATE(52), 1,
      sym_expression,
    STATE(149), 1,
      sym__wexpressionw,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [605] = 9,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      sym__w,
    STATE(21), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    STATE(144), 1,
      sym_comma_separated_expressions,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [639] = 9,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      sym__w,
    STATE(36), 1,
      sym_unary_operator,
    STATE(52), 1,
      sym_expression,
    STATE(147), 1,
      sym__wexpressionw,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [673] = 9,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      sym__w,
    STATE(36), 1,
      sym_unary_operator,
    STATE(52), 1,
      sym_expression,
    STATE(148), 1,
      sym__wexpressionw,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [707] = 12,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(135), 1,
      sym__w,
    STATE(35), 1,
      sym_binary_operator,
    STATE(48), 1,
      sym_wcommaw,
    STATE(81), 1,
      aux_sym_comma_separated_expressions_repeat1,
    STATE(133), 1,
      sym_wcomma,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [746] = 8,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(141), 1,
      sym__w,
    STATE(27), 1,
      sym_unary_operator,
    STATE(59), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(139), 2,
      sym_identifier,
      sym_literal,
    STATE(63), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(67), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [777] = 8,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      sym__w,
    STATE(31), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [808] = 3,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(147), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(145), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [829] = 8,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    STATE(146), 1,
      sym_comma_separated_expressions,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [860] = 8,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    STATE(136), 1,
      sym_comma_separated_expressions,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [891] = 8,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(149), 1,
      sym__w,
    STATE(27), 1,
      sym_unary_operator,
    STATE(56), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(139), 2,
      sym_identifier,
      sym_literal,
    STATE(63), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(67), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [922] = 8,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(151), 1,
      sym__linebreak,
    STATE(36), 1,
      sym_unary_operator,
    STATE(57), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [953] = 8,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      sym__w,
    STATE(27), 1,
      sym_unary_operator,
    STATE(61), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(139), 2,
      sym_identifier,
      sym_literal,
    STATE(63), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(67), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [984] = 3,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(157), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(155), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [1005] = 3,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(161), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(159), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [1026] = 3,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(165), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(163), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [1047] = 3,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(169), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(167), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [1068] = 8,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 1,
      sym__w,
    STATE(27), 1,
      sym_unary_operator,
    STATE(51), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(139), 2,
      sym_identifier,
      sym_literal,
    STATE(63), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(67), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1099] = 8,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(173), 1,
      sym__w,
    STATE(32), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1130] = 8,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(175), 1,
      sym__w,
    STATE(33), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1161] = 7,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_unary_operator,
    STATE(61), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(139), 2,
      sym_identifier,
      sym_literal,
    STATE(63), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(67), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1189] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    STATE(36), 1,
      sym_unary_operator,
    STATE(53), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1217] = 7,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_unary_operator,
    STATE(54), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(139), 2,
      sym_identifier,
      sym_literal,
    STATE(63), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(67), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1245] = 2,
    ACTIONS(179), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(177), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [1263] = 7,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_unary_operator,
    STATE(55), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(139), 2,
      sym_identifier,
      sym_literal,
    STATE(63), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(67), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1291] = 2,
    ACTIONS(183), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(181), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [1309] = 2,
    ACTIONS(187), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(185), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [1327] = 2,
    ACTIONS(191), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(189), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [1345] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    STATE(24), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1373] = 2,
    ACTIONS(195), 2,
      aux_sym_binary_operator_token1,
      sym__iw,
    ACTIONS(193), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      sym__w,
  [1391] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1419] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    STATE(36), 1,
      sym_unary_operator,
    STATE(60), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1447] = 7,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_expression,
    STATE(36), 1,
      sym_unary_operator,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(109), 2,
      sym_identifier,
      sym_literal,
    STATE(40), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(44), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1475] = 7,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_unary_operator,
    STATE(58), 1,
      sym_expression,
    ACTIONS(107), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(139), 2,
      sym_identifier,
      sym_literal,
    STATE(63), 2,
      sym_unary_operation,
      sym_binary_operation,
    STATE(67), 4,
      sym_container,
      sym_call,
      sym_operation,
      sym__atom,
  [1503] = 10,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    ACTIONS(199), 1,
      anon_sym_LPAREN,
    ACTIONS(201), 1,
      anon_sym_LBRACK,
    ACTIONS(203), 1,
      sym__w,
    ACTIONS(205), 1,
      sym__iw,
    ACTIONS(207), 1,
      sym__linebreak,
    STATE(22), 1,
      sym_binary_operator,
    STATE(138), 1,
      sym__lineend,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1536] = 8,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(211), 1,
      sym__w,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(209), 3,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1565] = 8,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(215), 1,
      sym__w,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(213), 3,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1594] = 10,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(197), 1,
      anon_sym_LBRACE,
    ACTIONS(199), 1,
      anon_sym_LPAREN,
    ACTIONS(201), 1,
      anon_sym_LBRACK,
    ACTIONS(203), 1,
      sym__w,
    ACTIONS(205), 1,
      sym__iw,
    ACTIONS(217), 1,
      sym__linebreak,
    STATE(22), 1,
      sym_binary_operator,
    STATE(135), 1,
      sym__lineend,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1627] = 3,
    STATE(22), 1,
      sym_binary_operator,
    ACTIONS(157), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(155), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1645] = 3,
    STATE(22), 1,
      sym_binary_operator,
    ACTIONS(169), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(167), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1663] = 9,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    ACTIONS(221), 1,
      sym__w,
    ACTIONS(223), 1,
      sym__iw,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1693] = 3,
    STATE(22), 1,
      sym_binary_operator,
    ACTIONS(147), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(145), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1711] = 3,
    STATE(22), 1,
      sym_binary_operator,
    ACTIONS(165), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(163), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1729] = 8,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(221), 1,
      sym__w,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(225), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1757] = 3,
    STATE(22), 1,
      sym_binary_operator,
    ACTIONS(161), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(159), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1775] = 9,
    ACTIONS(121), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      anon_sym_LBRACK,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(221), 1,
      sym__w,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    ACTIONS(229), 1,
      sym__iw,
    STATE(35), 1,
      sym_binary_operator,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1805] = 2,
    ACTIONS(179), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(177), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1820] = 5,
    ACTIONS(235), 1,
      sym__iw,
    STATE(70), 1,
      aux_sym_plain_text_inline_repeat1,
    STATE(127), 1,
      sym__text_separator,
    ACTIONS(233), 3,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
    ACTIONS(231), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
  [1841] = 5,
    ACTIONS(235), 1,
      sym__iw,
    STATE(64), 1,
      aux_sym_plain_text_inline_repeat1,
    STATE(127), 1,
      sym__text_separator,
    ACTIONS(239), 3,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
    ACTIONS(237), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
  [1862] = 2,
    ACTIONS(183), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(181), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1877] = 2,
    ACTIONS(191), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(189), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1892] = 2,
    ACTIONS(187), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(185), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1907] = 2,
    ACTIONS(195), 4,
      aux_sym_binary_operator_token1,
      sym__w,
      sym__iw,
      sym__linebreak,
    ACTIONS(193), 6,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1922] = 5,
    ACTIONS(245), 1,
      sym__iw,
    STATE(70), 1,
      aux_sym_plain_text_inline_repeat1,
    STATE(127), 1,
      sym__text_separator,
    ACTIONS(243), 3,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
    ACTIONS(241), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
  [1943] = 2,
    ACTIONS(241), 4,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
    ACTIONS(243), 4,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      sym__iw,
  [1956] = 4,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    STATE(23), 1,
      sym_binary_operator,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(213), 3,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1973] = 4,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    STATE(23), 1,
      sym_binary_operator,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(248), 3,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1990] = 3,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    ACTIONS(254), 1,
      sym__w,
    ACTIONS(250), 5,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_identifier,
      sym_literal,
  [2004] = 3,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    ACTIONS(260), 1,
      sym__w,
    ACTIONS(256), 5,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_identifier,
      sym_literal,
  [2018] = 1,
    ACTIONS(93), 7,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_identifier,
      sym_literal,
      sym__w,
  [2028] = 5,
    ACTIONS(262), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(264), 1,
      aux_sym__anyline_token1,
    ACTIONS(266), 1,
      sym__linebreak,
    STATE(11), 1,
      sym_fence,
    STATE(86), 2,
      sym__anyline,
      aux_sym_code_repeat1,
  [2045] = 1,
    ACTIONS(268), 6,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_identifier,
      sym_literal,
      sym__w,
  [2054] = 5,
    ACTIONS(262), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(264), 1,
      aux_sym__anyline_token1,
    ACTIONS(270), 1,
      sym__linebreak,
    STATE(10), 1,
      sym_fence,
    STATE(77), 2,
      sym__anyline,
      aux_sym_code_repeat1,
  [2071] = 4,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      sym_binary_operator,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2086] = 6,
    ACTIONS(123), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    ACTIONS(276), 1,
      sym__w,
    STATE(48), 1,
      sym_wcommaw,
    STATE(90), 1,
      aux_sym_comma_separated_expressions_repeat1,
    STATE(131), 1,
      sym_wcomma,
  [2105] = 2,
    ACTIONS(260), 1,
      sym__w,
    ACTIONS(256), 5,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_identifier,
      sym_literal,
  [2116] = 2,
    ACTIONS(254), 1,
      sym__w,
    ACTIONS(250), 5,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_identifier,
      sym_literal,
  [2127] = 1,
    ACTIONS(278), 6,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_identifier,
      sym_literal,
      sym__w,
  [2136] = 3,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    STATE(23), 1,
      sym_binary_operator,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2148] = 4,
    ACTIONS(280), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(282), 1,
      aux_sym__anyline_token1,
    ACTIONS(285), 1,
      sym__linebreak,
    STATE(86), 2,
      sym__anyline,
      aux_sym_code_repeat1,
  [2162] = 1,
    ACTIONS(288), 5,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_identifier,
      sym_literal,
  [2170] = 1,
    ACTIONS(256), 5,
      anon_sym_LPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      sym_identifier,
      sym_literal,
  [2178] = 3,
    ACTIONS(131), 1,
      aux_sym_binary_operator_token1,
    STATE(29), 1,
      sym_binary_operator,
    ACTIONS(133), 3,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [2190] = 5,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      sym__w,
    STATE(48), 1,
      sym_wcommaw,
    STATE(90), 1,
      aux_sym_comma_separated_expressions_repeat1,
  [2206] = 4,
    ACTIONS(296), 1,
      sym__iw,
    ACTIONS(299), 1,
      sym__linebreak,
    STATE(4), 1,
      sym__text_separator,
    STATE(91), 1,
      aux_sym__text_inline_repeat1,
  [2219] = 4,
    ACTIONS(301), 1,
      sym_fence_tag,
    ACTIONS(303), 1,
      sym__iw,
    ACTIONS(305), 1,
      sym__linebreak,
    STATE(111), 1,
      sym__lineend,
  [2232] = 4,
    ACTIONS(307), 1,
      sym__iw,
    ACTIONS(309), 1,
      sym__linebreak,
    STATE(4), 1,
      sym__text_separator,
    STATE(94), 1,
      aux_sym__text_inline_repeat1,
  [2245] = 4,
    ACTIONS(307), 1,
      sym__iw,
    ACTIONS(311), 1,
      sym__linebreak,
    STATE(4), 1,
      sym__text_separator,
    STATE(91), 1,
      aux_sym__text_inline_repeat1,
  [2258] = 4,
    ACTIONS(313), 1,
      sym_fence_tag,
    ACTIONS(315), 1,
      sym__iw,
    ACTIONS(317), 1,
      sym__linebreak,
    STATE(6), 1,
      sym__lineend,
  [2271] = 1,
    ACTIONS(319), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2277] = 1,
    ACTIONS(321), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2283] = 2,
    ACTIONS(325), 1,
      sym__linebreak,
    ACTIONS(323), 2,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      aux_sym__anyline_token1,
  [2291] = 3,
    ACTIONS(315), 1,
      sym__iw,
    ACTIONS(327), 1,
      sym__linebreak,
    STATE(7), 1,
      sym__lineend,
  [2301] = 1,
    ACTIONS(329), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2307] = 2,
    ACTIONS(93), 1,
      sym__linebreak,
    ACTIONS(95), 2,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      aux_sym__anyline_token1,
  [2315] = 2,
    ACTIONS(85), 1,
      sym__linebreak,
    ACTIONS(87), 2,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      aux_sym__anyline_token1,
  [2323] = 2,
    ACTIONS(331), 1,
      sym__text_punctuation,
    ACTIONS(333), 2,
      sym__iw,
      sym__linebreak,
  [2331] = 1,
    ACTIONS(335), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2337] = 1,
    ACTIONS(337), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2343] = 1,
    ACTIONS(339), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2349] = 1,
    ACTIONS(341), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2355] = 1,
    ACTIONS(343), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2361] = 3,
    ACTIONS(303), 1,
      sym__iw,
    ACTIONS(345), 1,
      sym__linebreak,
    STATE(102), 1,
      sym__lineend,
  [2371] = 1,
    ACTIONS(347), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2377] = 2,
    ACTIONS(81), 1,
      sym__linebreak,
    ACTIONS(83), 2,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      aux_sym__anyline_token1,
  [2385] = 1,
    ACTIONS(349), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2391] = 1,
    ACTIONS(351), 3,
      sym__text_punctuation,
      sym__iw,
      sym__linebreak,
  [2397] = 2,
    ACTIONS(353), 1,
      sym__text_word,
    STATE(130), 1,
      sym_plain_text_inline,
  [2404] = 1,
    ACTIONS(355), 2,
      sym__iw,
      sym__linebreak,
  [2409] = 2,
    ACTIONS(353), 1,
      sym__text_word,
    STATE(126), 1,
      sym_plain_text_inline,
  [2416] = 2,
    ACTIONS(353), 1,
      sym__text_word,
    STATE(139), 1,
      sym_plain_text_inline,
  [2423] = 2,
    ACTIONS(353), 1,
      sym__text_word,
    STATE(141), 1,
      sym_plain_text_inline,
  [2430] = 2,
    ACTIONS(353), 1,
      sym__text_word,
    STATE(151), 1,
      sym_plain_text_inline,
  [2437] = 2,
    ACTIONS(353), 1,
      sym__text_word,
    STATE(153), 1,
      sym_plain_text_inline,
  [2444] = 1,
    ACTIONS(299), 2,
      sym__iw,
      sym__linebreak,
  [2449] = 2,
    ACTIONS(353), 1,
      sym__text_word,
    STATE(128), 1,
      sym_plain_text_inline,
  [2456] = 1,
    ACTIONS(357), 2,
      sym__iw,
      sym__linebreak,
  [2461] = 1,
    ACTIONS(359), 1,
      ts_builtin_sym_end,
  [2465] = 1,
    ACTIONS(361), 1,
      anon_sym_RBRACE,
  [2469] = 1,
    ACTIONS(363), 1,
      anon_sym_STAR,
  [2473] = 1,
    ACTIONS(365), 1,
      sym__text_word,
  [2477] = 1,
    ACTIONS(363), 1,
      anon_sym____,
  [2481] = 1,
    ACTIONS(367), 1,
      sym__linebreak,
  [2485] = 1,
    ACTIONS(363), 1,
      anon_sym_TILDE_TILDE,
  [2489] = 1,
    ACTIONS(369), 1,
      anon_sym_RPAREN,
  [2493] = 1,
    ACTIONS(272), 1,
      anon_sym_COMMA,
  [2497] = 1,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
  [2501] = 1,
    ACTIONS(371), 1,
      sym__linebreak,
  [2505] = 1,
    ACTIONS(373), 1,
      anon_sym_RBRACE,
  [2509] = 1,
    ACTIONS(375), 1,
      anon_sym_RPAREN,
  [2513] = 1,
    ACTIONS(377), 1,
      sym__linebreak,
  [2517] = 1,
    ACTIONS(379), 1,
      anon_sym_RBRACE,
  [2521] = 1,
    ACTIONS(363), 1,
      anon_sym__,
  [2525] = 1,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
  [2529] = 1,
    ACTIONS(363), 1,
      anon_sym_STAR_STAR,
  [2533] = 1,
    ACTIONS(361), 1,
      anon_sym_RBRACK,
  [2537] = 1,
    ACTIONS(381), 1,
      sym__linebreak,
  [2541] = 1,
    ACTIONS(383), 1,
      anon_sym_RPAREN,
  [2545] = 1,
    ACTIONS(361), 1,
      anon_sym_RPAREN,
  [2549] = 1,
    ACTIONS(385), 1,
      anon_sym_RPAREN,
  [2553] = 1,
    ACTIONS(387), 1,
      anon_sym_RBRACE,
  [2557] = 1,
    ACTIONS(387), 1,
      anon_sym_RPAREN,
  [2561] = 1,
    ACTIONS(387), 1,
      anon_sym_RBRACK,
  [2565] = 1,
    ACTIONS(151), 1,
      sym__linebreak,
  [2569] = 1,
    ACTIONS(363), 1,
      anon_sym___,
  [2573] = 1,
    ACTIONS(389), 1,
      anon_sym_RBRACE,
  [2577] = 1,
    ACTIONS(363), 1,
      anon_sym_STAR_STAR_STAR,
  [2581] = 1,
    ACTIONS(391), 1,
      anon_sym_RPAREN,
  [2585] = 1,
    ACTIONS(393), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 79,
  [SMALL_STATE(4)] = 158,
  [SMALL_STATE(5)] = 212,
  [SMALL_STATE(6)] = 266,
  [SMALL_STATE(7)] = 288,
  [SMALL_STATE(8)] = 310,
  [SMALL_STATE(9)] = 332,
  [SMALL_STATE(10)] = 354,
  [SMALL_STATE(11)] = 376,
  [SMALL_STATE(12)] = 398,
  [SMALL_STATE(13)] = 435,
  [SMALL_STATE(14)] = 469,
  [SMALL_STATE(15)] = 503,
  [SMALL_STATE(16)] = 537,
  [SMALL_STATE(17)] = 571,
  [SMALL_STATE(18)] = 605,
  [SMALL_STATE(19)] = 639,
  [SMALL_STATE(20)] = 673,
  [SMALL_STATE(21)] = 707,
  [SMALL_STATE(22)] = 746,
  [SMALL_STATE(23)] = 777,
  [SMALL_STATE(24)] = 808,
  [SMALL_STATE(25)] = 829,
  [SMALL_STATE(26)] = 860,
  [SMALL_STATE(27)] = 891,
  [SMALL_STATE(28)] = 922,
  [SMALL_STATE(29)] = 953,
  [SMALL_STATE(30)] = 984,
  [SMALL_STATE(31)] = 1005,
  [SMALL_STATE(32)] = 1026,
  [SMALL_STATE(33)] = 1047,
  [SMALL_STATE(34)] = 1068,
  [SMALL_STATE(35)] = 1099,
  [SMALL_STATE(36)] = 1130,
  [SMALL_STATE(37)] = 1161,
  [SMALL_STATE(38)] = 1189,
  [SMALL_STATE(39)] = 1217,
  [SMALL_STATE(40)] = 1245,
  [SMALL_STATE(41)] = 1263,
  [SMALL_STATE(42)] = 1291,
  [SMALL_STATE(43)] = 1309,
  [SMALL_STATE(44)] = 1327,
  [SMALL_STATE(45)] = 1345,
  [SMALL_STATE(46)] = 1373,
  [SMALL_STATE(47)] = 1391,
  [SMALL_STATE(48)] = 1419,
  [SMALL_STATE(49)] = 1447,
  [SMALL_STATE(50)] = 1475,
  [SMALL_STATE(51)] = 1503,
  [SMALL_STATE(52)] = 1536,
  [SMALL_STATE(53)] = 1565,
  [SMALL_STATE(54)] = 1594,
  [SMALL_STATE(55)] = 1627,
  [SMALL_STATE(56)] = 1645,
  [SMALL_STATE(57)] = 1663,
  [SMALL_STATE(58)] = 1693,
  [SMALL_STATE(59)] = 1711,
  [SMALL_STATE(60)] = 1729,
  [SMALL_STATE(61)] = 1757,
  [SMALL_STATE(62)] = 1775,
  [SMALL_STATE(63)] = 1805,
  [SMALL_STATE(64)] = 1820,
  [SMALL_STATE(65)] = 1841,
  [SMALL_STATE(66)] = 1862,
  [SMALL_STATE(67)] = 1877,
  [SMALL_STATE(68)] = 1892,
  [SMALL_STATE(69)] = 1907,
  [SMALL_STATE(70)] = 1922,
  [SMALL_STATE(71)] = 1943,
  [SMALL_STATE(72)] = 1956,
  [SMALL_STATE(73)] = 1973,
  [SMALL_STATE(74)] = 1990,
  [SMALL_STATE(75)] = 2004,
  [SMALL_STATE(76)] = 2018,
  [SMALL_STATE(77)] = 2028,
  [SMALL_STATE(78)] = 2045,
  [SMALL_STATE(79)] = 2054,
  [SMALL_STATE(80)] = 2071,
  [SMALL_STATE(81)] = 2086,
  [SMALL_STATE(82)] = 2105,
  [SMALL_STATE(83)] = 2116,
  [SMALL_STATE(84)] = 2127,
  [SMALL_STATE(85)] = 2136,
  [SMALL_STATE(86)] = 2148,
  [SMALL_STATE(87)] = 2162,
  [SMALL_STATE(88)] = 2170,
  [SMALL_STATE(89)] = 2178,
  [SMALL_STATE(90)] = 2190,
  [SMALL_STATE(91)] = 2206,
  [SMALL_STATE(92)] = 2219,
  [SMALL_STATE(93)] = 2232,
  [SMALL_STATE(94)] = 2245,
  [SMALL_STATE(95)] = 2258,
  [SMALL_STATE(96)] = 2271,
  [SMALL_STATE(97)] = 2277,
  [SMALL_STATE(98)] = 2283,
  [SMALL_STATE(99)] = 2291,
  [SMALL_STATE(100)] = 2301,
  [SMALL_STATE(101)] = 2307,
  [SMALL_STATE(102)] = 2315,
  [SMALL_STATE(103)] = 2323,
  [SMALL_STATE(104)] = 2331,
  [SMALL_STATE(105)] = 2337,
  [SMALL_STATE(106)] = 2343,
  [SMALL_STATE(107)] = 2349,
  [SMALL_STATE(108)] = 2355,
  [SMALL_STATE(109)] = 2361,
  [SMALL_STATE(110)] = 2371,
  [SMALL_STATE(111)] = 2377,
  [SMALL_STATE(112)] = 2385,
  [SMALL_STATE(113)] = 2391,
  [SMALL_STATE(114)] = 2397,
  [SMALL_STATE(115)] = 2404,
  [SMALL_STATE(116)] = 2409,
  [SMALL_STATE(117)] = 2416,
  [SMALL_STATE(118)] = 2423,
  [SMALL_STATE(119)] = 2430,
  [SMALL_STATE(120)] = 2437,
  [SMALL_STATE(121)] = 2444,
  [SMALL_STATE(122)] = 2449,
  [SMALL_STATE(123)] = 2456,
  [SMALL_STATE(124)] = 2461,
  [SMALL_STATE(125)] = 2465,
  [SMALL_STATE(126)] = 2469,
  [SMALL_STATE(127)] = 2473,
  [SMALL_STATE(128)] = 2477,
  [SMALL_STATE(129)] = 2481,
  [SMALL_STATE(130)] = 2485,
  [SMALL_STATE(131)] = 2489,
  [SMALL_STATE(132)] = 2493,
  [SMALL_STATE(133)] = 2497,
  [SMALL_STATE(134)] = 2501,
  [SMALL_STATE(135)] = 2505,
  [SMALL_STATE(136)] = 2509,
  [SMALL_STATE(137)] = 2513,
  [SMALL_STATE(138)] = 2517,
  [SMALL_STATE(139)] = 2521,
  [SMALL_STATE(140)] = 2525,
  [SMALL_STATE(141)] = 2529,
  [SMALL_STATE(142)] = 2533,
  [SMALL_STATE(143)] = 2537,
  [SMALL_STATE(144)] = 2541,
  [SMALL_STATE(145)] = 2545,
  [SMALL_STATE(146)] = 2549,
  [SMALL_STATE(147)] = 2553,
  [SMALL_STATE(148)] = 2557,
  [SMALL_STATE(149)] = 2561,
  [SMALL_STATE(150)] = 2565,
  [SMALL_STATE(151)] = 2569,
  [SMALL_STATE(152)] = 2573,
  [SMALL_STATE(153)] = 2577,
  [SMALL_STATE(154)] = 2581,
  [SMALL_STATE(155)] = 2585,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(92),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(116),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(117),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(118),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(119),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(120),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(122),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(114),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(100),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(103),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(12),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(96),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(5),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence, 2),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence, 2),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fence, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fence, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__text_line, 2),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__text_line, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lineend, 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lineend, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_separated_expressions, 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operation, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operation, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operation, 5),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operation, 5),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operation, 4),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operation, 4),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operation, 3),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operation, 3),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operation, 2),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operation, 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operation, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operation, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_container, 3),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_container, 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_container, 4),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_container, 4),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(150),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__wexpressionw, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__wexpressionw, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT(135),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(152),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_separated_expressions_repeat1, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plain_text_inline, 2),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_text_inline, 2),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plain_text_inline, 1),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_text_inline, 1),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_plain_text_inline_repeat1, 2),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_plain_text_inline_repeat1, 2),
  [245] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_plain_text_inline_repeat1, 2), SHIFT_REPEAT(127),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__wexpressionw, 3),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wcommaw, 1),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wcomma, 1),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wcommaw, 2),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wcomma, 2),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 1),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_separated_expressions, 2),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operator, 1),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2),
  [282] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2), SHIFT_REPEAT(137),
  [285] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2), SHIFT_REPEAT(86),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wcommaw, 3),
  [290] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_separated_expressions_repeat1, 2), SHIFT_REPEAT(83),
  [293] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_separated_expressions_repeat1, 2), SHIFT_REPEAT(155),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__text_inline_repeat1, 2), SHIFT_REPEAT(4),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__text_inline_repeat1, 2),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__text_inline, 1),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__text_inline, 2),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_latex_math, 1),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_block_parse, 6),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__anyline, 2),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__anyline, 2),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_token, 1),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__text_token, 1),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_inline_parse, 3),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parse_token, 1),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_parse, 1),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_parse, 1),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_inline_parse, 5),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_inline_parse, 4),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_token, 3),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_block_parse, 5),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__first_text_token, 2),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__text_token, 2),
  [359] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [369] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_separated_expressions, 3),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [385] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [389] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [391] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_mson(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
