#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  sym_comment = 1,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 2,
  aux_sym_rule_token1 = 3,
  anon_sym_COLON = 4,
  aux_sym_rule_token2 = 5,
  anon_sym_POUND = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_DASH = 9,
  anon_sym_PLUS = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_COMMA = 13,
  anon_sym_LPAREN2 = 14,
  anon_sym_LT = 15,
  anon_sym_GT = 16,
  anon_sym_EQ = 17,
  anon_sym_BANG_EQ = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_SLASH = 21,
  anon_sym_STAR = 22,
  anon_sym_COLON_EQ = 23,
  sym_literal = 24,
  anon_sym_LBRACK = 25,
  anon_sym_RBRACK = 26,
  anon_sym__ = 27,
  sym_myword = 28,
  sym_punctuation = 29,
  sym_source_file = 30,
  sym__block = 31,
  sym_code = 32,
  sym_rule = 33,
  sym_structure = 34,
  sym_heading = 35,
  sym_text = 36,
  sym_math = 37,
  sym_explicit_math = 38,
  sym_implicit_math = 39,
  sym_unary_operation = 40,
  sym_binary_operation = 41,
  sym__expression = 42,
  sym_parenthesised = 43,
  sym_comma_separated_expressions = 44,
  sym_pair = 45,
  sym_call = 46,
  sym_math_operator = 47,
  sym_atom = 48,
  sym_identifier = 49,
  sym_bracket = 50,
  sym_nonmath = 51,
  sym_nonword = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_code_repeat1 = 54,
  aux_sym_heading_repeat1 = 55,
  aux_sym_text_repeat1 = 56,
  aux_sym_comma_separated_expressions_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [aux_sym_rule_token1] = "rule_token1",
  [anon_sym_COLON] = ":",
  [aux_sym_rule_token2] = "rule_token2",
  [anon_sym_POUND] = "#",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_SLASH] = "/",
  [anon_sym_STAR] = "*",
  [anon_sym_COLON_EQ] = ":=",
  [sym_literal] = "literal",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym__] = "_",
  [sym_myword] = "myword",
  [sym_punctuation] = "punctuation",
  [sym_source_file] = "source_file",
  [sym__block] = "_block",
  [sym_code] = "code",
  [sym_rule] = "rule",
  [sym_structure] = "structure",
  [sym_heading] = "heading",
  [sym_text] = "text",
  [sym_math] = "math",
  [sym_explicit_math] = "explicit_math",
  [sym_implicit_math] = "implicit_math",
  [sym_unary_operation] = "unary_operation",
  [sym_binary_operation] = "binary_operation",
  [sym__expression] = "_expression",
  [sym_parenthesised] = "parenthesised",
  [sym_comma_separated_expressions] = "comma_separated_expressions",
  [sym_pair] = "pair",
  [sym_call] = "call",
  [sym_math_operator] = "math_operator",
  [sym_atom] = "atom",
  [sym_identifier] = "identifier",
  [sym_bracket] = "bracket",
  [sym_nonmath] = "nonmath",
  [sym_nonword] = "nonword",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
  [aux_sym_heading_repeat1] = "heading_repeat1",
  [aux_sym_text_repeat1] = "text_repeat1",
  [aux_sym_comma_separated_expressions_repeat1] = "comma_separated_expressions_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [aux_sym_rule_token1] = aux_sym_rule_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_rule_token2] = aux_sym_rule_token2,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_literal] = sym_literal,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym__] = anon_sym__,
  [sym_myword] = sym_myword,
  [sym_punctuation] = sym_punctuation,
  [sym_source_file] = sym_source_file,
  [sym__block] = sym__block,
  [sym_code] = sym_code,
  [sym_rule] = sym_rule,
  [sym_structure] = sym_structure,
  [sym_heading] = sym_heading,
  [sym_text] = sym_text,
  [sym_math] = sym_math,
  [sym_explicit_math] = sym_explicit_math,
  [sym_implicit_math] = sym_implicit_math,
  [sym_unary_operation] = sym_unary_operation,
  [sym_binary_operation] = sym_binary_operation,
  [sym__expression] = sym__expression,
  [sym_parenthesised] = sym_parenthesised,
  [sym_comma_separated_expressions] = sym_comma_separated_expressions,
  [sym_pair] = sym_pair,
  [sym_call] = sym_call,
  [sym_math_operator] = sym_math_operator,
  [sym_atom] = sym_atom,
  [sym_identifier] = sym_identifier,
  [sym_bracket] = sym_bracket,
  [sym_nonmath] = sym_nonmath,
  [sym_nonword] = sym_nonword,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
  [aux_sym_heading_repeat1] = aux_sym_heading_repeat1,
  [aux_sym_text_repeat1] = aux_sym_text_repeat1,
  [aux_sym_comma_separated_expressions_repeat1] = aux_sym_comma_separated_expressions_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_rule_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_rule_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym_myword] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_structure] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_math] = {
    .visible = true,
    .named = true,
  },
  [sym_explicit_math] = {
    .visible = true,
    .named = true,
  },
  [sym_implicit_math] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operation] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operation] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesised] = {
    .visible = true,
    .named = true,
  },
  [sym_comma_separated_expressions] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_math_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_nonmath] = {
    .visible = true,
    .named = true,
  },
  [sym_nonword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_separated_expressions_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(15)
      if (lookahead == '!') ADVANCE(52);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '=') ADVANCE(39);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '_') ADVANCE(49);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '"' ||
          (';' <= lookahead && lookahead <= '?')) ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(4);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(5);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(45);
      END_STATE();
    case 10:
      if (lookahead == '`') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == '`') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(13)
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '=') ADVANCE(39);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '_') ADVANCE(49);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(13)
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '<') ADVANCE(37);
      if (lookahead == '=') ADVANCE(39);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '_') ADVANCE(49);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(14)
      if (lookahead == ':') ADVANCE(24);
      END_STATE();
    case 15:
      if (eof) ADVANCE(19);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(15)
      if (lookahead == '!') ADVANCE(52);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == ',') ADVANCE(34);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '=') ADVANCE(39);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '_') ADVANCE(49);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '"' ||
          (';' <= lookahead && lookahead <= '?')) ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 16:
      if (eof) ADVANCE(19);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(16)
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '<') ADVANCE(2);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '!' ||
          lookahead == '"' ||
          (',' <= lookahead && lookahead <= '.') ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '?') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(18)
      if (lookahead == '!') ADVANCE(52);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '=') ADVANCE(39);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '_') ADVANCE(49);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '"' ||
          (',' <= lookahead && lookahead <= '.') ||
          (';' <= lookahead && lookahead <= '?')) ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(18)
      if (lookahead == '!') ADVANCE(52);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '(') ADVANCE(32);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == ':') ADVANCE(53);
      if (lookahead == '<') ADVANCE(36);
      if (lookahead == '=') ADVANCE(39);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == '_') ADVANCE(49);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '"' ||
          (',' <= lookahead && lookahead <= '.') ||
          (';' <= lookahead && lookahead <= '?')) ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_rule_token1);
      if (lookahead == '.') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_rule_token1);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_rule_token2);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_rule_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_myword);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '=') ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 17},
  [9] = {.lex_state = 17},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 17},
  [15] = {.lex_state = 17},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 17},
  [23] = {.lex_state = 17},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 12},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 12},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 17},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 16},
  [40] = {.lex_state = 16},
  [41] = {.lex_state = 16},
  [42] = {.lex_state = 16},
  [43] = {.lex_state = 16},
  [44] = {.lex_state = 17},
  [45] = {.lex_state = 16},
  [46] = {.lex_state = 16},
  [47] = {.lex_state = 17},
  [48] = {.lex_state = 16},
  [49] = {.lex_state = 16},
  [50] = {.lex_state = 16},
  [51] = {.lex_state = 16},
  [52] = {.lex_state = 16},
  [53] = {.lex_state = 17},
  [54] = {.lex_state = 16},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 17},
  [57] = {.lex_state = 12},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 17},
  [61] = {.lex_state = 16},
  [62] = {.lex_state = 16},
  [63] = {.lex_state = 16},
  [64] = {.lex_state = 16},
  [65] = {.lex_state = 16},
  [66] = {.lex_state = 16},
  [67] = {.lex_state = 16},
  [68] = {.lex_state = 16},
  [69] = {.lex_state = 16},
  [70] = {.lex_state = 12},
  [71] = {.lex_state = 12},
  [72] = {.lex_state = 12},
  [73] = {.lex_state = 12},
  [74] = {.lex_state = 12},
  [75] = {.lex_state = 12},
  [76] = {.lex_state = 16},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 16},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [aux_sym_rule_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym_myword] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(79),
    [sym__block] = STATE(2),
    [sym_code] = STATE(2),
    [sym_structure] = STATE(2),
    [sym_heading] = STATE(64),
    [sym_text] = STATE(2),
    [sym_math] = STATE(5),
    [sym_explicit_math] = STATE(62),
    [sym_implicit_math] = STATE(62),
    [sym_unary_operation] = STATE(60),
    [sym_binary_operation] = STATE(16),
    [sym__expression] = STATE(60),
    [sym_parenthesised] = STATE(60),
    [sym_pair] = STATE(16),
    [sym_call] = STATE(16),
    [sym_atom] = STATE(60),
    [sym_identifier] = STATE(26),
    [sym_bracket] = STATE(16),
    [sym_nonmath] = STATE(5),
    [sym_nonword] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_heading_repeat1] = STATE(10),
    [aux_sym_text_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_literal] = ACTIONS(17),
    [sym_myword] = ACTIONS(19),
    [sym_punctuation] = ACTIONS(21),
  },
  [2] = {
    [sym__block] = STATE(3),
    [sym_code] = STATE(3),
    [sym_structure] = STATE(3),
    [sym_heading] = STATE(64),
    [sym_text] = STATE(3),
    [sym_math] = STATE(5),
    [sym_explicit_math] = STATE(62),
    [sym_implicit_math] = STATE(62),
    [sym_unary_operation] = STATE(60),
    [sym_binary_operation] = STATE(16),
    [sym__expression] = STATE(60),
    [sym_parenthesised] = STATE(60),
    [sym_pair] = STATE(16),
    [sym_call] = STATE(16),
    [sym_atom] = STATE(60),
    [sym_identifier] = STATE(26),
    [sym_bracket] = STATE(16),
    [sym_nonmath] = STATE(5),
    [sym_nonword] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_heading_repeat1] = STATE(10),
    [aux_sym_text_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_comment] = ACTIONS(25),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_literal] = ACTIONS(17),
    [sym_myword] = ACTIONS(19),
    [sym_punctuation] = ACTIONS(21),
  },
  [3] = {
    [sym__block] = STATE(3),
    [sym_code] = STATE(3),
    [sym_structure] = STATE(3),
    [sym_heading] = STATE(64),
    [sym_text] = STATE(3),
    [sym_math] = STATE(5),
    [sym_explicit_math] = STATE(62),
    [sym_implicit_math] = STATE(62),
    [sym_unary_operation] = STATE(60),
    [sym_binary_operation] = STATE(16),
    [sym__expression] = STATE(60),
    [sym_parenthesised] = STATE(60),
    [sym_pair] = STATE(16),
    [sym_call] = STATE(16),
    [sym_atom] = STATE(60),
    [sym_identifier] = STATE(26),
    [sym_bracket] = STATE(16),
    [sym_nonmath] = STATE(5),
    [sym_nonword] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_heading_repeat1] = STATE(10),
    [aux_sym_text_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_comment] = ACTIONS(29),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(32),
    [anon_sym_POUND] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(38),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(44),
    [sym_literal] = ACTIONS(47),
    [sym_myword] = ACTIONS(50),
    [sym_punctuation] = ACTIONS(53),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(58), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      sym_literal,
    ACTIONS(70), 1,
      sym_myword,
    ACTIONS(73), 1,
      sym_punctuation,
    STATE(17), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(62), 2,
      sym_explicit_math,
      sym_implicit_math,
    STATE(4), 3,
      sym_math,
      sym_nonmath,
      aux_sym_text_repeat1,
    ACTIONS(56), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
    STATE(16), 4,
      sym_binary_operation,
      sym_pair,
      sym_call,
      sym_bracket,
    STATE(60), 4,
      sym_unary_operation,
      sym__expression,
      sym_parenthesised,
      sym_atom,
  [53] = 13,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(19), 1,
      sym_myword,
    ACTIONS(21), 1,
      sym_punctuation,
    STATE(17), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(62), 2,
      sym_explicit_math,
      sym_implicit_math,
    STATE(4), 3,
      sym_math,
      sym_nonmath,
      aux_sym_text_repeat1,
    ACTIONS(76), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
    STATE(16), 4,
      sym_binary_operation,
      sym_pair,
      sym_call,
      sym_bracket,
    STATE(60), 4,
      sym_unary_operation,
      sym__expression,
      sym_parenthesised,
      sym_atom,
  [106] = 2,
    ACTIONS(80), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(78), 21,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_myword,
  [136] = 2,
    ACTIONS(84), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(82), 21,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_myword,
  [166] = 2,
    ACTIONS(88), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(86), 21,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_myword,
  [196] = 2,
    ACTIONS(92), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(90), 21,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_myword,
  [226] = 15,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(19), 1,
      sym_myword,
    ACTIONS(21), 1,
      sym_punctuation,
    ACTIONS(94), 1,
      anon_sym_POUND,
    STATE(17), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    STATE(66), 1,
      sym_text,
    STATE(68), 1,
      aux_sym_heading_repeat1,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(62), 2,
      sym_explicit_math,
      sym_implicit_math,
    STATE(5), 3,
      sym_math,
      sym_nonmath,
      aux_sym_text_repeat1,
    STATE(16), 4,
      sym_binary_operation,
      sym_pair,
      sym_call,
      sym_bracket,
    STATE(60), 4,
      sym_unary_operation,
      sym__expression,
      sym_parenthesised,
      sym_atom,
  [282] = 4,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    STATE(51), 1,
      sym_math_operator,
    ACTIONS(98), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(96), 17,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      sym_myword,
  [314] = 4,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    STATE(51), 1,
      sym_math_operator,
    ACTIONS(104), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(102), 17,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      sym_myword,
  [346] = 3,
    ACTIONS(110), 1,
      anon_sym__,
    ACTIONS(108), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(106), 18,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      sym_myword,
  [376] = 5,
    ACTIONS(110), 1,
      anon_sym__,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(114), 2,
      anon_sym_LPAREN,
      sym_punctuation,
    ACTIONS(112), 7,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      sym_literal,
      sym_myword,
    ACTIONS(106), 11,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [410] = 2,
    ACTIONS(118), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(116), 18,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      sym_myword,
  [437] = 4,
    ACTIONS(124), 2,
      anon_sym_LPAREN,
      sym_punctuation,
    ACTIONS(126), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(120), 7,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      sym_literal,
      sym_myword,
    ACTIONS(122), 11,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [468] = 4,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(114), 2,
      anon_sym_LPAREN,
      sym_punctuation,
    ACTIONS(112), 7,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      sym_literal,
      sym_myword,
    ACTIONS(106), 11,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [499] = 2,
    ACTIONS(108), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(106), 18,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      sym_myword,
  [526] = 2,
    ACTIONS(130), 4,
      anon_sym_LPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_punctuation,
    ACTIONS(128), 18,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      sym_literal,
      anon_sym_LBRACK,
      sym_myword,
  [553] = 2,
    ACTIONS(118), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(116), 15,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [575] = 8,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_LPAREN2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    STATE(50), 1,
      sym_math_operator,
    STATE(74), 1,
      aux_sym_comma_separated_expressions_repeat1,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [609] = 4,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    STATE(36), 1,
      sym_math_operator,
    ACTIONS(104), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(102), 13,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [635] = 3,
    ACTIONS(110), 1,
      anon_sym__,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 14,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [659] = 2,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 15,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [681] = 4,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    STATE(36), 1,
      sym_math_operator,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(96), 13,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [707] = 2,
    ACTIONS(130), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(128), 15,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [729] = 7,
    ACTIONS(138), 1,
      anon_sym_LPAREN2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [760] = 8,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    STATE(78), 1,
      sym_comma_separated_expressions,
    ACTIONS(148), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(21), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [793] = 6,
    ACTIONS(138), 1,
      anon_sym_LPAREN2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    STATE(50), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(154), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [822] = 3,
    ACTIONS(156), 1,
      anon_sym__,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(106), 13,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [845] = 4,
    ACTIONS(138), 1,
      anon_sym_LPAREN2,
    STATE(50), 1,
      sym_math_operator,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(96), 12,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [870] = 7,
    ACTIONS(138), 1,
      anon_sym_LPAREN2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(144), 1,
      anon_sym_RPAREN,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [901] = 7,
    ACTIONS(138), 1,
      anon_sym_LPAREN2,
    ACTIONS(142), 1,
      anon_sym_LBRACK,
    ACTIONS(158), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [932] = 8,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    STATE(81), 1,
      sym_comma_separated_expressions,
    ACTIONS(148), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(21), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [965] = 4,
    ACTIONS(138), 1,
      anon_sym_LPAREN2,
    STATE(50), 1,
      sym_math_operator,
    ACTIONS(104), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(102), 12,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [990] = 7,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(162), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(22), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1020] = 6,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(166), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [1048] = 7,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(148), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(27), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1078] = 7,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(162), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(56), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1108] = 7,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(148), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(31), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1138] = 7,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(162), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(47), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1168] = 7,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(162), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(53), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1198] = 7,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(162), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(37), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1228] = 6,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(168), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [1256] = 7,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(162), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(25), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1286] = 7,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(148), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(32), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1316] = 6,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(170), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [1344] = 7,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(148), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(29), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1374] = 7,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(148), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(33), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1404] = 7,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(148), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(35), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1434] = 7,
    ACTIONS(174), 1,
      anon_sym_LPAREN,
    ACTIONS(176), 1,
      sym_literal,
    ACTIONS(178), 1,
      sym_myword,
    STATE(18), 1,
      sym_nonword,
    STATE(19), 1,
      sym_identifier,
    ACTIONS(172), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(12), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1464] = 7,
    ACTIONS(15), 1,
      anon_sym_LPAREN,
    ACTIONS(17), 1,
      sym_literal,
    ACTIONS(162), 1,
      sym_myword,
    STATE(24), 1,
      sym_nonword,
    STATE(26), 1,
      sym_identifier,
    ACTIONS(13), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(44), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1494] = 6,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [1522] = 7,
    ACTIONS(174), 1,
      anon_sym_LPAREN,
    ACTIONS(176), 1,
      sym_literal,
    ACTIONS(178), 1,
      sym_myword,
    STATE(18), 1,
      sym_nonword,
    STATE(19), 1,
      sym_identifier,
    ACTIONS(172), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    STATE(11), 8,
      sym_unary_operation,
      sym_binary_operation,
      sym__expression,
      sym_parenthesised,
      sym_pair,
      sym_call,
      sym_atom,
      sym_bracket,
  [1552] = 2,
    ACTIONS(88), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(86), 13,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [1572] = 6,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [1600] = 2,
    ACTIONS(84), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(82), 13,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [1620] = 2,
    ACTIONS(80), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(78), 13,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [1640] = 2,
    ACTIONS(92), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(90), 13,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
      anon_sym_LBRACK,
  [1660] = 5,
    ACTIONS(100), 1,
      anon_sym_LPAREN2,
    ACTIONS(164), 1,
      anon_sym_LBRACK,
    STATE(51), 1,
      sym_math_operator,
    ACTIONS(140), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(132), 9,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_SLASH,
      anon_sym_STAR,
      anon_sym_COLON_EQ,
  [1685] = 1,
    ACTIONS(184), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      sym_literal,
      sym_myword,
      sym_punctuation,
  [1699] = 1,
    ACTIONS(186), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      sym_literal,
      sym_myword,
      sym_punctuation,
  [1713] = 1,
    ACTIONS(188), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      sym_literal,
      sym_myword,
      sym_punctuation,
  [1727] = 1,
    ACTIONS(190), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      sym_literal,
      sym_myword,
      sym_punctuation,
  [1741] = 1,
    ACTIONS(192), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      sym_literal,
      sym_myword,
      sym_punctuation,
  [1755] = 1,
    ACTIONS(194), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      sym_literal,
      sym_myword,
      sym_punctuation,
  [1769] = 1,
    ACTIONS(112), 11,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      anon_sym_POUND,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      sym_literal,
      sym_myword,
      sym_punctuation,
  [1783] = 3,
    ACTIONS(196), 1,
      anon_sym_POUND,
    STATE(68), 1,
      aux_sym_heading_repeat1,
    ACTIONS(199), 7,
      anon_sym_LBRACE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      sym_literal,
      sym_myword,
      sym_punctuation,
  [1799] = 1,
    ACTIONS(201), 5,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      sym_literal,
      sym_myword,
  [1807] = 3,
    ACTIONS(203), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(205), 1,
      aux_sym_rule_token1,
    STATE(71), 2,
      sym_rule,
      aux_sym_code_repeat1,
  [1818] = 3,
    ACTIONS(207), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(209), 1,
      aux_sym_rule_token1,
    STATE(71), 2,
      sym_rule,
      aux_sym_code_repeat1,
  [1829] = 3,
    ACTIONS(205), 1,
      aux_sym_rule_token1,
    ACTIONS(212), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(70), 2,
      sym_rule,
      aux_sym_code_repeat1,
  [1840] = 3,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_comma_separated_expressions_repeat1,
  [1850] = 3,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_comma_separated_expressions_repeat1,
  [1860] = 1,
    ACTIONS(219), 2,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      aux_sym_rule_token1,
  [1865] = 1,
    ACTIONS(221), 1,
      sym_myword,
  [1869] = 1,
    ACTIONS(223), 1,
      anon_sym_COLON,
  [1873] = 1,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
  [1877] = 1,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
  [1881] = 1,
    ACTIONS(229), 1,
      aux_sym_rule_token2,
  [1885] = 1,
    ACTIONS(231), 1,
      anon_sym_RPAREN,
  [1889] = 1,
    ACTIONS(233), 1,
      sym_myword,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 53,
  [SMALL_STATE(6)] = 106,
  [SMALL_STATE(7)] = 136,
  [SMALL_STATE(8)] = 166,
  [SMALL_STATE(9)] = 196,
  [SMALL_STATE(10)] = 226,
  [SMALL_STATE(11)] = 282,
  [SMALL_STATE(12)] = 314,
  [SMALL_STATE(13)] = 346,
  [SMALL_STATE(14)] = 376,
  [SMALL_STATE(15)] = 410,
  [SMALL_STATE(16)] = 437,
  [SMALL_STATE(17)] = 468,
  [SMALL_STATE(18)] = 499,
  [SMALL_STATE(19)] = 526,
  [SMALL_STATE(20)] = 553,
  [SMALL_STATE(21)] = 575,
  [SMALL_STATE(22)] = 609,
  [SMALL_STATE(23)] = 635,
  [SMALL_STATE(24)] = 659,
  [SMALL_STATE(25)] = 681,
  [SMALL_STATE(26)] = 707,
  [SMALL_STATE(27)] = 729,
  [SMALL_STATE(28)] = 760,
  [SMALL_STATE(29)] = 793,
  [SMALL_STATE(30)] = 822,
  [SMALL_STATE(31)] = 845,
  [SMALL_STATE(32)] = 870,
  [SMALL_STATE(33)] = 901,
  [SMALL_STATE(34)] = 932,
  [SMALL_STATE(35)] = 965,
  [SMALL_STATE(36)] = 990,
  [SMALL_STATE(37)] = 1020,
  [SMALL_STATE(38)] = 1048,
  [SMALL_STATE(39)] = 1078,
  [SMALL_STATE(40)] = 1108,
  [SMALL_STATE(41)] = 1138,
  [SMALL_STATE(42)] = 1168,
  [SMALL_STATE(43)] = 1198,
  [SMALL_STATE(44)] = 1228,
  [SMALL_STATE(45)] = 1256,
  [SMALL_STATE(46)] = 1286,
  [SMALL_STATE(47)] = 1316,
  [SMALL_STATE(48)] = 1344,
  [SMALL_STATE(49)] = 1374,
  [SMALL_STATE(50)] = 1404,
  [SMALL_STATE(51)] = 1434,
  [SMALL_STATE(52)] = 1464,
  [SMALL_STATE(53)] = 1494,
  [SMALL_STATE(54)] = 1522,
  [SMALL_STATE(55)] = 1552,
  [SMALL_STATE(56)] = 1572,
  [SMALL_STATE(57)] = 1600,
  [SMALL_STATE(58)] = 1620,
  [SMALL_STATE(59)] = 1640,
  [SMALL_STATE(60)] = 1660,
  [SMALL_STATE(61)] = 1685,
  [SMALL_STATE(62)] = 1699,
  [SMALL_STATE(63)] = 1713,
  [SMALL_STATE(64)] = 1727,
  [SMALL_STATE(65)] = 1741,
  [SMALL_STATE(66)] = 1755,
  [SMALL_STATE(67)] = 1769,
  [SMALL_STATE(68)] = 1783,
  [SMALL_STATE(69)] = 1799,
  [SMALL_STATE(70)] = 1807,
  [SMALL_STATE(71)] = 1818,
  [SMALL_STATE(72)] = 1829,
  [SMALL_STATE(73)] = 1840,
  [SMALL_STATE(74)] = 1850,
  [SMALL_STATE(75)] = 1860,
  [SMALL_STATE(76)] = 1865,
  [SMALL_STATE(77)] = 1869,
  [SMALL_STATE(78)] = 1873,
  [SMALL_STATE(79)] = 1877,
  [SMALL_STATE(80)] = 1881,
  [SMALL_STATE(81)] = 1885,
  [SMALL_STATE(82)] = 1889,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(72),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(10),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(39),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(45),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(46),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(26),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(67),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2), SHIFT_REPEAT(39),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2), SHIFT_REPEAT(45),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2), SHIFT_REPEAT(46),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2), SHIFT_REPEAT(26),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2), SHIFT_REPEAT(14),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_repeat1, 2), SHIFT_REPEAT(67),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket, 4),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket, 4),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 5),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 5),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nonword, 3),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nonword, 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operation, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operation, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operation, 3),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operation, 3),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nonmath, 1),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nonmath, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesised, 3),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesised, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_implicit_math, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_implicit_math, 1),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_separated_expressions, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comma_separated_expressions_repeat1, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 3),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_structure, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_explicit_math, 3),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 2),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2), SHIFT_REPEAT(68),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_operator, 1),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2), SHIFT_REPEAT(77),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comma_separated_expressions_repeat1, 2), SHIFT_REPEAT(48),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comma_separated_expressions, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [227] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_mson(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
